---
- hosts: all
  tasks:
  - name:  multiple items.
    file: 
      state:  touch 
      path:  /home/{{ansible_ssh_user}}/{{ item }}
    loop:
      - file_no_1
      - file_no_2
      - file_no_3


